### ISSUE TITLE
[Q] Can the Gmi generation part be put as a theme?

### ISSUE THREAD

**Issue by xplshn** [hedyhli/site#1]
I looked around the net all day for a Gemini config for Hugo and finally found your repo, could you explain a bit how I could use this too? I have my site at https://fatbuffalo.neocities.org/def/ and want to offer it as a Gemini capsule too.

**Comment by hedyhli** [comment]
Hey there, feel free to use my site as inspiration for setting up Gemini using Hugo.

The tutorial I followed is from Drew DeVault. Since Drew has recently moved off of Gemini, this tutorial is no longer available on his server, however, I have recently archived his gemini content, so you can find it here: https://hedy.nand.sh/ddevault/Gemini-and-Hugo.html

Additional resources include this post made by bacardi55: https://bacardi55.io/2021/02/13/managing-this-site-and-my-gemini-capsule-with-hugo/

Note though, regarding "Ugly URLs" (ie: `/my-post.html` vs `/my-post/`). You have some cool posts on the site you linked -- I noticed non-ugly URLs are used. When I configure `uglyurls = false` in `config.toml`, the `/my-post/` style is used for **both HTML and Gemini**. I didn't want that (I want `/my-post/` for HTML and `/my-post.gmi` for Gemini), this doesn't seem to be possible with Hugo, so I had to convert non-ugly URLs to ugly URLs for Gemini content manually using this script myself:
https://github.com/hedyhli/site/blob/e52b48c3b18d03f491aa52397d74dd1de3b24ae8/bin/gemini-clean.py#L69-L95

**Comment by xplshn** [comment]
Okay. Thanks for all the info!
